---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: abc
  label: New Doc
  match: "**/*"
- type: heading
  label: Heading
- type: directory
  path: la
  label: New Dir
  create: all
  match: "**/*"
  templates:
  - new-template
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
